apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cba-prod

resources:
  - ../../base/cba-was-renewal
  - ingress.yaml

patches:
  - path: patches/deployment-replicas.yaml
  - path: patches/deployment-image.yaml
