apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-ingress.yaml
  - argocd-controller-service-monitor.yaml
  - argocd-server-service-monitor.yaml
  - argocd-repo-service-monitor.yaml
  - argocd-applicationset-service-monitor.yaml
  - argocd-notifications-service-monitor.yaml
  - argocd-dashboard.yaml
