fullnameOverride: cba-management

replicaCount: 1

image:
  repository: ap-chuncheon-1.ocir.io/axdhp42jvukm/cba_management_v2
  tag: latest_dev
  pullPolicy: Always

imagePullSecrets:
  - name: ocir-secret

serviceAccount:
  create: false
  name: ""

container:
  name: cba-management
  port: 80
  portName: http

envFrom: []

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 80
  portName: http

readinessProbe:
  enabled: true
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 3
  periodSeconds: 10

livenessProbe:
  enabled: true
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 10
  periodSeconds: 20

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 256Mi

ingress:
  enabled: false
