apiVersion: apps/v1
kind: Deployment
metadata:
  name: cba-management
  labels:
    app: cba-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cba-management
  template:
    metadata:
      labels:
        app: cba-management
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: cba-management
          image: ap-chuncheon-1.ocir.io/axdhp42jvukm/cba_management_v2:latest_dev
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi
