apiVersion: v1
kind: Service
metadata:
  name: cba-management
  labels:
    app: cba-management
spec:
  type: ClusterIP
  selector:
    app: cba-management
  ports:
    - name: http
      port: 80
      targetPort: 80
