redis:
  enabled: true
  auth:
    enabled: true
    existingSecret: redis-auth
    passwordKey: password
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: oci-bv

rabbitmq:
  enabled: true
  auth:
    username: cba
    existingSecret: rabbitmq-auth
    passwordKey: password
  persistence:
    enabled: true
    size: 20Gi
    storageClassName: oci-bv
