apiVersion: apps/v1
kind: Deployment
metadata:
  name: cba-was-renewal
  labels:
    app: cba-was-renewal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cba-was-renewal
  template:
    metadata:
      labels:
        app: cba-was-renewal
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: cba-was-renewal
          image: ap-chuncheon-1.ocir.io/axdhp42jvukm/cba_was_renew:latest_dev
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - secretRef:
                name: cba-was-renewal-env
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi
