alertmanager:
  enabled: false

coreDns:
  enabled: false

grafana:
  enabled: true
  defaultDashboardsTimezone: Asia/Seoul
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 384Mi
  persistence:
    enabled: true
    type: pvc
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 5Gi
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - monitoring.dev.recba.me
    path: /
    pathType: Prefix
  grafana.ini:
    server:
      domain: monitoring.dev.recba.me
      root_url: https://monitoring.dev.recba.me
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: false

kubeScheduler:
  enabled: false

kube-state-metrics:
  resources:
    requests:
      cpu: 30m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 192Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 96Mi

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 300m
      memory: 300Mi

prometheus:
  prometheusSpec:
    replicas: 1
    retention: 7d
    retentionSize: 8GB
    walCompression: true
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1536Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
