apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cba-was-renewal-prod
  namespace: argocd
spec:
  project: cba-connect-prod
  source:
    repoURL: https://github.com/dpcomm/cba_infra.git
    targetRevision: main
    path: charts/cba-app
    helm:
      releaseName: cba-was-renewal
      valueFiles:
        - values/prod/cba-was-renewal.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cba-connect-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  revisionHistoryLimit: 10
