apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cba-connect-prod
  namespace: argocd
spec:
  description: CBA Connect production workloads
  sourceRepos:
    - https://github.com/dpcomm/cba_infra.git
  destinations:
    - namespace: cba-connect-prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
