apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project.yaml
  - cba-was-renewal.yaml
  - cba-email-worker.yaml
  - cba-push-worker.yaml
  - cba-management.yaml
  - monitoring.yaml
  - observability-config.yaml
