apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-config-dev
  namespace: argocd
spec:
  project: cba-connect-dev
  source:
    repoURL: https://github.com/dpcomm/cba_infra.git
    targetRevision: main
    path: monitoring/dev/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
  revisionHistoryLimit: 5
