apiVersion: apps/v1
kind: Deployment
metadata:
  name: cba-was-renewal-push-worker
  labels:
    app: cba-was-renewal-push-worker
    component: worker
    worker: push
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cba-was-renewal-push-worker
  template:
    metadata:
      labels:
        app: cba-was-renewal-push-worker
        component: worker
        worker: push
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: push-worker
          image: ap-chuncheon-1.ocir.io/axdhp42jvukm/cba_was_renew:latest_dev
          imagePullPolicy: Always
          command: ["node"]
          args: ["dist/apps/push-worker/src/main.js"]
          envFrom:
            - secretRef:
                name: cba-was-renewal-env
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi
