apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cba-dev

resources:
  - ../../base/cba-management
  - ../../base/cba-was-renewal
  - cba-was-renewal-email-worker.yaml
  - cba-was-renewal-push-worker.yaml
  - ingress.yaml
